name: Dynamo Binary Diff

on:
  workflow_run:
    workflows:
      - Build DynamoAll.sln net8.0
    types:
      - completed

jobs:
  binary_diff:
    name: Binary Diff
    runs-on: windows-latest
    steps:
      - name: Download Pull Request Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: pr_data
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          path: ${{ github.workspace }}\pr
      - name: Read Pull Request Data
        run: |
          "PR_NUMBER=$(Get-Content -Path ${{ github.workspace }}\pr\pr_number.txt)" | Out-File -FilePath $env:GITHUB_ENV -Append
          "CACHE_KEY=$(Get-Content -Path ${{ github.workspace }}\pr\cache_key.txt)" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Restore Master Build
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          path: |
            ${{ github.workspace }}\master\bin\AnyCPU\Release
            ${{ github.workspace }}\master\.github\scripts
          key: DynamoSandbox-master
      - name: Restore Current Build
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          path: ${{ github.workspace }}\current\bin\AnyCPU\Release
          key: ${{ env.CACHE_KEY }}
      - name: Run Binary Diff
        id: bin_diff
        run: |
          echo "***Running the binary diff job between the current branch and the master branch!***"
          cd "$Env:GITHUB_WORKSPACE\master\.github\scripts"
          .\bin_diff.ps1 $Env:GITHUB_WORKSPACE\master\bin\AnyCPU\Release, $Env:GITHUB_WORKSPACE\current\bin\AnyCPU\Release -src ${{ github.job }}
          "diff=$(Get-Content -Path ${{ github.workspace }}\result.txt)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: 'github-actions[bot]'
          body-includes: Files Added/Deleted
          direction: last
      - name: Create Comment
        if: ${{ steps.find_comment.outputs.comment-id == '' }} && ${{ steps.bin_diff.outputs.diff != '' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ env.PR_NUMBER }}
          body: ${{ steps.bin_diff.outputs.diff }}
      - name: Update Comment
        if: ${{ steps.find_comment.outputs.comment-id != '' }} && ${{ steps.bin_diff.outputs.diff != '' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            ${{ steps.bin_diff.outputs.diff }}
            (Updated: $(Get-Date -format yyyy-MM-dd-HH:mm:ss))
      - name: Update Comment as Resolved
        if: ${{ steps.find_comment.outputs.comment-id != '' }} && ${{ steps.bin_diff.outputs.diff == '' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            ":white_check_mark: **Binary Diff Issue Resolved.**"
            (Updated: $(Get-Date -format yyyy-MM-dd-HH:mm:ss))
      - name: Delete Build Cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh cache delete ${{ env.CACHE_KEY }} -R ${{ github.repository }} || true
