name: UI Smoke Tests

on:
  workflow_run:
    workflows:
      - Build DynamoAll.sln net6.0
      - Build DynamoAll.sln net8.0
    types:
      - completed

env:
  TEST_EXECUTE_DOWNLOAD_URL: https://downloads.smartbear.com/TestExecute1552SLM.exe
  ACTOR: ${{ github.actor }}
  WORKFLOW_ID: ${{ github.event.workflow_run.workflow_id }}
  RUN_ID: ${{ github.event.workflow_run.id }}
  RUN_NAME: ${{ github.event.workflow_run.name }}
  RUN_URL: ${{ github.event.workflow_run.html_url }}

jobs:
  ui_smoke_tests:
    name: UI Smoke Tests
    timeout-minutes: 60
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: DynamoDS/DynamoTestCompleteTests
          token: ${{ secrets.DYNAMO_TESTS_TOKEN }}
          ref: master
      - name: Download TestExecute
        run: Invoke-WebRequest -Uri "${{ env.TEST_EXECUTE_DOWNLOAD_URL }}" -OutFile ".\TE.exe"
      - name: Install TestExecute
        shell: cmd
        run: .\TE.exe -SilentInstall
      - name: Download Build Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: DynamoSandbox
          workflow: ${{ env.WORKFLOW_ID }}
          run_id: ${{ env.RUN_ID }}
          path: ${{ github.workspace }}\build
      - name: Download Pull Request Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: pr_number
          workflow: ${{ env.WORKFLOW_ID }}
          run_id: ${{ env.RUN_ID }}
          path: ${{ github.workspace }}\pr
      - name: Run UI Smoke Tests
        shell: cmd
        run: .github\scripts\run_tests.bat ${{ secrets.TEST_EXECUTE_ACCESS_KEY }} Dynamo\Dynamo.pjs DynamoSandbox SmokeTests
      - name: Set Check Name
        id: set_check_name
        run: |
          "check_name=$("UI Smoke Tests", $($env:RUN_NAME -Split " ")[-1] -Join " - ")" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: UI Smoke Tests Report
        id: test_report
        uses: dorny/test-reporter@v1.7.0
        if: always()
        with:
          name: ${{ steps.set_check_name.outputs.check_name }}
          path: reports/report.xml
          reporter: java-junit
      - name: Read Pull Request Number
        id: read_pr_number
        run: |
          "pr_number=$(Get-Content -Path ${{ github.workspace }}\pr\pr_number.txt)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: Summary
        env:
          PR_NUMBER: ${{ steps.read_pr_number.outputs.pr_number }}
          PR_URL: ${{ format('{0}/{1}/pull', github.server_url, github.repository) }}
        if: always()
        run: |
          if (Test-Path -Path summary.md) {
            Get-Content -Path summary.md | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }
          "## Run Summary" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          "Actor: @$env:ACTOR" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          "Workflow Run: [$env:RUN_NAME]($env:RUN_URL)" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          if ($env:PR_NUMBER) {
            "Pull Request: [#$env:PR_NUMBER]($env:PR_URL/$env:PR_NUMBER)" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }
          "Check: [${{ steps.set_check_name.outputs.check_name }}](${{ steps.test_report.outputs.url_html }})" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
      - name: Add Pull Request Comment
        if: always()
        env:
          GH_TOKEN: ${{ secrets.DYNAMO_TESTS_TOKEN }}
        run: |
          if ($env:PR_NUMBER) {
            $pr_comment=@"
            ## UI Smoke Tests
            Test: ${{ steps.test_report.outputs.conclusion }}. ${{ steps.test_report.outputs.passed }} passed, ${{ steps.test_report.outputs.failed }} failed.
            [TestComplete Test Result]($(Get-Content -Path ${{ github.workspace }}\reports\result.txt))
            Workflow Run: [${{ github.event.workflow.name }}](${{ github.event.workflow.html_url}})
            Check: [${{ steps.set_check_name.outputs.check_name }}](${{ steps.test_report.outputs.url_html }})
            "@
            gh pr comment $env:PR_NUMBER --body $pr_comment --repo DynamoDS/Dynamo
          }
